// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('IbaarAutmation', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('IbaarAutmation', async function() {
    await driver.get("https://front.ibaar.ir/apps/dashboards/analytics")
    await driver.manage().window().setRect({ width: 1006, height: 933 })
    {
      const element = await driver.findElement(By.css(".jss317"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".jss317")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".jss882 .jss804")).click()
    {
      const element = await driver.findElement(By.css(".jss883 .jss804"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".jss883 .jss804")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    {
      const element = await driver.findElement(By.css(".m-10 > .jss419"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".m-10 > .jss419")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.id("mui-63984")).click()
    await driver.findElement(By.id("mui-63984-option-0")).click()
    await driver.findElement(By.id("mui-41331")).click()
    await driver.findElement(By.id("mui-41331-option-0")).click()
    {
      const element = await driver.findElement(By.id("is_active"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.css(".jss1306:nth-child(1)"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.css("body")).click()
    await driver.findElement(By.css(".jss1306:nth-child(2)")).click()
    await driver.findElement(By.id("description")).click()
    {
      const element = await driver.findElement(By.css(".m-auto > .jss428 > .jss419"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.id("description")).sendKeys("....")
    await driver.findElement(By.css(".m-auto > .jss428 > .jss419")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
  })
})
